name: null
favicon: null
layout_spectrum: 0.8
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252525'
    - '#ababab'
    - '#3d3d3d'
    - '#585858'
    - '#c8c8c8'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: null
    url: null
